CREATE TABLE Player(
  name TEXT,
  position INTEGER,
  number INTEGER,
  team TEXT,
  age INTEGER
) ;
INSERT INTO Player VALUES ("Craig Breslow",1,32,"Red Sox",34);
INSERT INTO Player VALUES ("Clay Buchholz",1,11,"Red Sox",30);
INSERT INTO Player VALUES ("Joe Kelly",1,56,"Red Sox",26);
INSERT INTO Player VALUES ("Justin Masterson",1,63,"Red Sox",30);
INSERT INTO Player VALUES ("Wade Miley",1,20,"Red Sox",28);
INSERT INTO Player VALUES ("Edward Mujica",1,54,"Red Sox",30);
INSERT INTO Player VALUES ("Alexi Ogando",1,41,"Red Sox",31);
INSERT INTO Player VALUES ("Rick Porcello",1,22,"Red Sox",26);
INSERT INTO Player VALUES ("Robbie Ross Jr.",1,28,"Red Sox",25);
INSERT INTO Player VALUES ("Junichi Tazawa",1,36,"Red Sox",28);
INSERT INTO Player VALUES ("Koji Uehara",1,19,"Red Sox",40);
INSERT INTO Player VALUES ("Anthony Varvaro",1,46,"Red Sox",30);
INSERT INTO Player VALUES ("Ryan Hanigan",2,10,"Red Sox",34);
INSERT INTO Player VALUES ("Sandy Leon",2,3,"Red Sox",26);
INSERT INTO Player VALUES ("Xander Bogaerts",6,2,"Red Sox",22);
INSERT INTO Player VALUES ("Brock Holt",5,26,"Red Sox",26);
INSERT INTO Player VALUES ("Mike Napoli",3,12,"Red Sox",33);
INSERT INTO Player VALUES ("Dustin Pedroia",4,15,"Red Sox",31);
INSERT INTO Player VALUES ("Pablo Sandoval",5,48,"Red Sox",28);
INSERT INTO Player VALUES ("Mookie Betts",7,50,"Red Sox",22);
INSERT INTO Player VALUES ("Jackie Bradley Jr.",8,25,"Red Sox",24);
INSERT INTO Player VALUES ("Allen Craig",9,5,"Red Sox",30);
INSERT INTO Player VALUES ("Daniel Nava",9,29,"Red Sox",32);
INSERT INTO Player VALUES ("Hanley Ramirez",7,13,"Red Sox",31);
INSERT INTO Player VALUES ("David Ortiz",10,34,"Red Sox",39);
INSERT INTO Player VALUES ("Brad Brach",1,35,"Orioles",28);
INSERT INTO Player VALUES ("Zach Britton",1,53,"Orioles",27);
INSERT INTO Player VALUES ("Wei-Yin Chen",1,16,"Orioles",30);
INSERT INTO Player VALUES ("Jason Garcia",1,61,"Orioles",22);
INSERT INTO Player VALUES ("Kevin Gausman",1,39,"Orioles",24);
INSERT INTO Player VALUES ("Miguel Gonzalez",1,50,"Orioles",31);
INSERT INTO Player VALUES ("Tommy Hunter",1,29,"Orioles",29);
INSERT INTO Player VALUES ("Ubaldo Jimenez",1,31,"Orioles",31);
INSERT INTO Player VALUES ("Brian Matusz",1,17,"Orioles",28);
INSERT INTO Player VALUES ("Bud Norris",1,25,"Orioles",30);
INSERT INTO Player VALUES ("Darren O'Day",1,56,"Orioles",33);
INSERT INTO Player VALUES ("Chris Tillman",1,30,"Orioles",27);
INSERT INTO Player VALUES ("Caleb Joseph",2,36,"Orioles",28);
INSERT INTO Player VALUES ("Ryan Lavarnway",2,34,"Orioles",27);
INSERT INTO Player VALUES ("Everth Cabrera",6,1,"Orioles",28);
INSERT INTO Player VALUES ("Chris Davis",3,19,"Orioles",29);
INSERT INTO Player VALUES ("Manny Machado",5,13,"Orioles",22);
INSERT INTO Player VALUES ("Rey Navarro",6,43,"Orioles",25);
INSERT INTO Player VALUES ("Jimmy Paredes",5,38,"Orioles",26);
INSERT INTO Player VALUES ("Alejandro De Aza",7,12,"Orioles",30);
INSERT INTO Player VALUES ("Adam Jones",8,10,"Orioles",29);
INSERT INTO Player VALUES ("David Lough",7,9,"Orioles",29);
INSERT INTO Player VALUES ("Steve Pearce",7,28,"Orioles",31);
INSERT INTO Player VALUES ("Travis Snider",9,23,"Orioles",27);
INSERT INTO Player VALUES ("Delmon Young",9,27,"Orioles",29);
INSERT INTO Player VALUES ("Dellin Betances",1,68,"Yankees",27);
INSERT INTO Player VALUES ("David Carpenter",1,29,"Yankees",29);
INSERT INTO Player VALUES ("Nathan Eovaldi",1,30,"Yankees",25);
INSERT INTO Player VALUES ("Chris Martin",1,57,"Yankees",28);
INSERT INTO Player VALUES ("Andrew Miller",1,48,"Yankees",29);
INSERT INTO Player VALUES ("Michael Pineda",1,35,"Yankees",26);
INSERT INTO Player VALUES ("Esmil Rogers",1,53,"Yankees",29);
INSERT INTO Player VALUES ("CC Sabathia",1,52,"Yankees",34);
INSERT INTO Player VALUES ("Chasen Shreve",1,45,"Yankees",24);
INSERT INTO Player VALUES ("Masahiro Tanaka",1,19,"Yankees",26);
INSERT INTO Player VALUES ("Adam Warren",1,43,"Yankees",27);
INSERT INTO Player VALUES ("Chase Whitley",1,39,"Yankees",25);
INSERT INTO Player VALUES ("Justin Wilson",1,41,"Yankees",27);
INSERT INTO Player VALUES ("Brian McCann",2,34,"Yankees",31);
INSERT INTO Player VALUES ("John Ryan Murphy",2,66,"Yankees",23);
INSERT INTO Player VALUES ("Alex Rodriguez",5,13,"Yankees",39);
INSERT INTO Player VALUES ("Brett Gardner",7,11,"Yankees",31);
INSERT INTO Player VALUES ("Carlos Beltran",9,36,"Yankees",37);
INSERT INTO Player VALUES ("Chase Headley",5,12,"Yankees",30);
INSERT INTO Player VALUES ("Chris Young",7,24,"Yankees",31);
INSERT INTO Player VALUES ("Didi Gregorius",6,18,"Yankees",25);
INSERT INTO Player VALUES ("Garrett Jones",3,33,"Yankees",33);
INSERT INTO Player VALUES ("Jacoby Ellsbury",8,22,"Yankees",31);
INSERT INTO Player VALUES ("Mark Teixeira",3,25,"Yankees",34);
INSERT INTO Player VALUES ("Stephen Drew",4,14,"Yankees",32);
INSERT INTO Player VALUES ("Mark Buehrle",1,56,"Blue Jays",36);
INSERT INTO Player VALUES ("Miguel Castro",1,51,"Blue Jays",20);
INSERT INTO Player VALUES ("Brett Cecil",1,27,"Blue Jays",28);
INSERT INTO Player VALUES ("R.A. Dickey",1,43,"Blue Jays",40);
INSERT INTO Player VALUES ("Marco Estrada",1,25,"Blue Jays",31);
INSERT INTO Player VALUES ("Jeff Francis",1,35,"Blue Jays",34);
INSERT INTO Player VALUES ("Liam Hendriks",1,31,"Blue Jays",26);
INSERT INTO Player VALUES ("Drew Hutchison",1,36,"Blue Jays",24);
INSERT INTO Player VALUES ("Aaron Loup",1,62,"Blue Jays",27);
INSERT INTO Player VALUES ("Daniel Norris",1,32,"Blue Jays",21);
INSERT INTO Player VALUES ("Roberto Osuna",1,54,"Blue Jays",20);
INSERT INTO Player VALUES ("Aaron Sanchez",1,41,"Blue Jays",22);
INSERT INTO Player VALUES ("Russell Martin",2,55,"Blue Jays",32);
INSERT INTO Player VALUES ("Josh Thole",2,22,"Blue Jays",28);
INSERT INTO Player VALUES ("Jonathan Diaz",6,1,"Blue Jays",29);
INSERT INTO Player VALUES ("Josh Donaldson",5,20,"Blue Jays",29);
INSERT INTO Player VALUES ("Edwin Encarnacion",3,10,"Blue Jays",32);
INSERT INTO Player VALUES ("Ryan Goins",4,17,"Blue Jays",27);
INSERT INTO Player VALUES ("Justin Smoak",3,14,"Blue Jays",28);
INSERT INTO Player VALUES ("Devon Travis",4,29,"Blue Jays",24);
INSERT INTO Player VALUES ("Danny Valencia",5,23,"Blue Jays",30);
INSERT INTO Player VALUES ("Jose Bautista",9,19,"Blue Jays",34);
INSERT INTO Player VALUES ("Kevin Pillar",7,11,"Blue Jays",26);
INSERT INTO Player VALUES ("Dalton Pompey",8,45,"Blue Jays",22);
INSERT INTO Player VALUES ("Michael Saunders",9,21,"Blue Jays",28);
INSERT INTO Player VALUES ("Matt Andriese",1,35,"Rays",25);
INSERT INTO Player VALUES ("Chris Archer",1,22,"Rays",26);
INSERT INTO Player VALUES ("Brad Boxberger",1,26,"Rays",26);
INSERT INTO Player VALUES ("Xavier Cedeno",1,31,"Rays",28);
INSERT INTO Player VALUES ("Ernesto Frieri",1,43,"Rays",29);
INSERT INTO Player VALUES ("Steve Geltz",1,54,"Rays",27);
INSERT INTO Player VALUES ("Brandon Gomes",1,47,"Rays",30);
INSERT INTO Player VALUES ("Kevin Jepsen",1,40,"Rays",30);
INSERT INTO Player VALUES ("Nathan Karns",1,51,"Rays",27);
INSERT INTO Player VALUES ("Jake Odorizzi",1,23,"Rays",25);
INSERT INTO Player VALUES ("Erasmo Ramirez",1,30,"Rays",24);
INSERT INTO Player VALUES ("Drew Smyly",1,33,"Rays",25);
INSERT INTO Player VALUES ("Rene Rivera",2,44,"Rays",31);
INSERT INTO Player VALUES ("Bobby Wilson",2,46,"Rays",31);
INSERT INTO Player VALUES ("Tim Beckham",4,1,"Rays",25);
INSERT INTO Player VALUES ("Asdrubal Cabrera",6,13,"Rays",29);
INSERT INTO Player VALUES ("Jake Elmore",6,10,"Rays",27);
INSERT INTO Player VALUES ("Logan Forsythe",4,11,"Rays",28);
INSERT INTO Player VALUES ("James Loney",3,21,"Rays",30);
INSERT INTO Player VALUES ("Evan Longoria",5,3,"Rays",29);
INSERT INTO Player VALUES ("David DeJesus",7,7,"Rays",35);
INSERT INTO Player VALUES ("Brandon Guyer",7,5,"Rays",29);
INSERT INTO Player VALUES ("Desmond Jennings",8,8,"Rays",28);
INSERT INTO Player VALUES ("Kevin Kiermaier",9,39,"Rays",24);
INSERT INTO Player VALUES ("Steven Souza  Jr.",9,20,"Rays",25);

.headers on
